export const GET_SHOPS_REQUESTED =  'GET_SHOPS_REQUESTED';
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const GET_SHOPS_FAILED = 'GET_SHOPS_FAILED'
export const GET_SHOPS_COUNT = 'GET_SHOPS_COUNT';
export const GET_SHOP_BY_ID_REQUESTED = 'GET_SHOP_BY_ID_REQUESTED';
export const PUT_SHOP_BY_ID = 'PUT_SHOP_BY_ID';
